### ISSUE TITLE
Rest API issue because of disabled MSI

### ISSUE THREAD

**Issue by alucardatem** [calcurates/module-magento#2]
Unfortunately i have found another bug in calcurates magento module. Noticed it as we are doing testing for epos integration.

in the webapi.xml we have the following:

<route url="/V1/calcurates/inventory/sources" method="GET"> <service class="Calcurates\ModuleMagento\Api\Source\SourceRepositoryInterface" method="getList"/> <resources> <resource ref="Magento_InventoryApi::source"/> </resources> </route>

However, people such as me ( will opt to remove Magento MSI functionality using composer, that means that the Magento_InventoryAPI is no longer on the system )

and the result for swagger is the following: swagger ha issue and can't render or work at all.

and with that commented out:

          

rest works again ( swagger)

**Comment by Gemorroj** [comment]
@NikolasSumrak please take a look

**Comment by Gemorroj** [comment]
fixed in https://github.com/calcurates/module-magento/commit/3b58c77e8109dd11b6a1ef4bbcfd936c713fb7db
