### ISSUE TITLE
Error when trying to install this module using the latest version

### ISSUE THREAD

**Issue by jakevegazzz** [calcurates/module-magento#4]
Magento Version: 2.3 and above
Used both manual and composer installation
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist.
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist.
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist.
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist.
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist.
Source class "\Calcurates\ModuleMagento\Model\Backend\Request\Data" for "Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor" generation does not exist

**Comment by vsevolod-tarasov** [comment]
Hello, tested module installation and the code entry point for Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor. We could not reproduce Your error. 
From error it is seems like Your magento 2 installation want to create the Calcurates\ModuleMagento\Model\Backend\Request\DataPersistor object  with same approach as Factory or Proxy classes which is not valid as it is basically the actual existing class.
If issue still persists please provide more accurate steps to reproduce it:
1. Actual magento 2 version( version number and type - Commerce/Open source)
2. screen or the list of folders present under vendor directory
3. composer.json file will be great.

Please check the output of bin/magento setup:di:compile
and bin/magento setup:upgrade commands. And if possible attach it to the issue
