### ISSUE TITLE
Error when sync origin Calcurates on magento 2.4.4

### ISSUE THREAD

**Issue by VuThuan** [calcurates/module-magento#5]
Hi dev, I have an issue when sync origin for magento 2.4.4
![image](https://user-images.githubusercontent.com/43930046/165880450-c8a3c4f7-6cf7-4c43-b946-37e2d0c2c267.png)
I configuration address for website here but it missing data when calcurates api
![image](https://user-images.githubusercontent.com/43930046/165880646-4329c453-c6e6-4334-bc6b-34a9d247022d.png)
![image](https://user-images.githubusercontent.com/43930046/165880756-89f39e14-d460-4701-99f2-590c05309439.png)
Can you check it for me ?

**Comment by vsevolod-tarasov** [comment]
Hello @VuThuan, those addresses which are used in Calcurates are configured through other place:
admin->stores->inventory->stocks - here is the connection between websites and sources
![image](https://user-images.githubusercontent.com/6348768/165948323-3e7a4036-9f8b-4590-9942-95e51b3b21be.png)
admin->stores->inventory->sources - here for each source the address should be set:
![image](https://user-images.githubusercontent.com/6348768/165948416-b5c63944-968c-4779-a3c9-fe9130f27a77.png)
![image](https://user-images.githubusercontent.com/6348768/165948452-6aafc5d3-7a68-4240-bd4d-78ad245a6a6e.png)
