### ISSUE TITLE
Possible logic error?

### ISSUE THREAD

**Issue by ivanaugustobd** [calcurates/module-magento#7]
Not sure if that's on purpose, but due to the absence of a `break 2` on 
https://github.com/calcurates/module-magento/blob/master/Client/MetaRatesResponseProcessor.php#L104
only the last rate is checked, overriding other checks that came before it:
```php
foreach ($response['origins'] as $origin) {
    foreach ($origin['shippingOptions'] ?? [] as $ratesGroupName => $ratesData) {
        if ($ratesData) {
            $shippingOptionsExist = true;
           // shouldn't be a "break 2" here? (or better, refactor to a dedicated method with an early return)
        }
    }
}
```

I'm debugging an unrelated issue (which seems to be custom theme-related though so I'm not reporting it for now) but who knows, that might affect some future edge-case scenario 🤷‍♂️

**Comment by Gemorroj** [comment]
@ivanaugustobd Thank you.
Yes, it seems we can break the loop, because subsequent iterations are meaningless. But in general, this does not violate logic.

**Comment by ivanaugustobd** [comment]
Wouldn't this risk a false positive in case all `$ratesData` but the last one are filled?

**Comment by Gemorroj** [comment]
@ivanaugustobd No.
We are only checking `$ratesData`. And if at least one variable gives the truth, then we switch `$shippingOptionsExist` to the truth too.

**Comment by ivanaugustobd** [comment]
That's what I thought when I saw this snippet, but with the current implementation the `$shippingOptionsExist` will be toggled back to `false` if the last one is empty, regardless of other shipping options existing. Consider a scenario like that, for example:

```php
$response = [
    // [..]
    'origins' => [
        123 => [
            // [..]
            'shippingOptions' => [
                // some data
            ]
        ],
        456 => [
            // [..]
            'shippingOptions' => null,
        ]
    ]
];
```

_In this case even with origin 123 containing shipping options, the `$shippingOptionsExist` variable will still be false_ due to being overridden by the last origin 456, which doesn't have such info in the hypothetical scenario above

But again, this didn't trigger any issues for me yet, just reported to potentially avoid future headaches with edge-case scenarios like that, no need to bother too much with this at the moment 🙂

**Comment by Gemorroj** [comment]
see https://3v4l.org/eY65U
The `$shippingOptionsExist` variable is defined before the loop with `$response['origins']`. Within future cycles, it can only switch to the truth.

**Comment by ivanaugustobd** [comment]
How could I be so blind, the `if` truly totally prevents that 🤦‍♂️
You're right, sorry for the trouble.
